/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.yarn;

import org.apache.hadoop.fs.Path;
import org.apache.hadoop.yarn.api.records.LocalResourceVisibility;

import javax.annotation.Nonnull;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Yarn local resource description is generated by {@link YarnClusterDescriptor} and set to environment of job manager.
 * Then it will be used to register local resources for task manager in {@link Utils#createTaskExecutorContext}.
 */
class YarnLocalResourceDescription {

	private static final String STRING_FORMAT = "YarnLocalResourceDescription{" +
		"key=%s, path=%s, size=%d, modificationTime=%d, visibility=%s}";
	private static final Pattern LOCAL_RESOURCE_DESC_FORMAT = Pattern.compile("YarnLocalResourceDescription\\{" +
		"key=(\\S+), path=(\\S+), size=([\\d]+), modificationTime=([\\d]+), visibility=(\\S+)}");

	private final String resourceKey;
	private final Path path;
	private long size;
	private long modificationTime;
	private LocalResourceVisibility visibility;

	YarnLocalResourceDescription(
		String resourceKey,
		Path path,
		long resourceSize,
		long modificationTime,
		LocalResourceVisibility visibility) {
		this.resourceKey = resourceKey;
		this.path = path;
		this.size = resourceSize;
		this.modificationTime = modificationTime;
		this.visibility = visibility;
	}

	String getResourceKey() {
		return resourceKey;
	}

	Path getPath() {
		return path;
	}

	long getSize() {
		return size;
	}

	long getModificationTime() {
		return modificationTime;
	}

	LocalResourceVisibility getVisibility() {
		return visibility;
	}

	@Nonnull
	static YarnLocalResourceDescription fromString(String desc) throws Exception {
		Matcher m = LOCAL_RESOURCE_DESC_FORMAT.matcher(desc);
		boolean mat = m.find();
		if (mat) {
			return new YarnLocalResourceDescription(
				m.group(1),
				new Path(m.group(2)),
				Long.parseLong(m.group(3)),
				Long.parseLong(m.group(4)),
				LocalResourceVisibility.valueOf(m.group(5)));
		} else {
			throw new Exception("Error to parse YarnLocalResourceDescription from " + desc);
		}
	}

	@Override
	public String toString() {
		return String.format(STRING_FORMAT, resourceKey, path.toString(), size, modificationTime, visibility);
	}
}
