name: "Worker Setup"
description: "Runs steps to set up the worker"

inputs:
  flink-checkout-folder:
    description: "The Flink checkout folder"
    required: true
  jdk-version:
    description: "JDK version to be installed"
    required: true
  maven-version:
    description: "Maven version to be installed"
    required: true
    default: 3.2.5
  ssl-enabled:
    description: "Installs SSL"
    required: false
  initial-disk-cleanup:
    description: "true, if a initial disk clean shall be performed"
    required: false
  additional-packages:
    description: "APT packages that shall be installed in addition to the default onces"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Free up disk space"
      if: inputs.initial-disk-cleanup == 'true'
      working-directory: ${{ inputs.flink-checkout-folder }}
      shell: bash
      run: ./tools/azure-pipelines/free_disk_space.sh

    # see https://github.com/actions/setup-java#supported-distributions
    - name: "Set JDK ${{ inputs.jdk-version }}"
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: ${{ inputs.jdk-version }}

    - name: "Install Maven ${{ inputs.maven-version }}"
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: "Install required dependencies bc and libapr1"
      shell: bash
      run: sudo apt-get install -y bc libapr1 ${{ inputs.additional-packages }}

    - name: "Install libssl1.0.0 for netty tcnative"
      if: inputs.ssl-enabled == 'true'
      shell: bash
      run: |
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.7_amd64.deb
        sudo apt install ./libssl1.0.0_1.0.2n-1ubuntu5.7_amd64.deb
