/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.formats.protobuf.typeutils;

import org.apache.flink.api.common.ExecutionConfig;
import org.apache.flink.api.common.typeutils.TypeSerializer;
import org.apache.flink.api.java.typeutils.GenericTypeInfo;

import com.google.protobuf.Message;

/**
 * Type information of message generated by protobuf.
 *
 * @param <T> The type of subclass of {@link Message}.
 */
public class ProtobufTypeInfo<T extends Message> extends GenericTypeInfo<T> {

	public ProtobufTypeInfo(Class<T> typeClass) {
		super(typeClass);
	}

	@Override
	public TypeSerializer<T> createSerializer(ExecutionConfig config) {
		return new ProtobufSerializer<>(getTypeClass(), config);
	}
}
