github:
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
notifications:
  commits:      commits@flink.apache.org
  issues:       issues@flink.apache.org
  pullrequests: issues@flink.apache.org
  jira_options: link label
