github:
  homepage: https://flink.apache.org/
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  labels:
    - flink
    - big-data
    - java
    - scala
    - python
    - sql
  collaborators:
    - flinkbot
notifications:
  commits:      commits@flink.apache.org
  issues:       issues@flink.apache.org
  pullrequests: issues@flink.apache.org
  jobs:         builds@flink.apache.org
  jira_options: link label
