github:
  homepage: https://flink.apache.org/
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  labels:
    - flink
    - big-data
    - java
    - scala
    - python
    - sql
  collaborators:
    - flinkbot
  rulesets:
    - name: "Default and Release Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release-*"
        excludes: [ ]
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits:      commits@flink.apache.org
  issues:       issues@flink.apache.org
  pullrequests: issues@flink.apache.org
  jobs:         builds@flink.apache.org
  jira_options: link label
