# Gitlab CI/CD
# Usage:
# 1. every git pull request will trigger build stage
# 2. Use gitlab schedules to trigger unit test & integration test

before_script:
  - echo "MAVEN_OPTS='-Xms4096m -Xmx4096m'" > ~/.mavenrc

stages:
  - build
  - test
  - deploy
  - manual_deploy
  - manual_upload
  - cleanup

build_job:
  stage: build
  only:
    - /\/.*-mdh\/.*/
  script:
    - mvn clean package -DskipTests -Dfast

unit_test:
  stage: test
  only:
    - /\/.*-mdh\/.*/
  script:
    - mvn test
  when: on_success

deploy_job:
  stage: deploy
  script:
    - sed -i 's/<shadeTestJar>true<\/shadeTestJar>/<shadeTestJar>false<\/shadeTestJar>/'  pom.xml
    - mvn deploy -s "tools/maven/settings.xml" -DskipTests -Dfast
  only:
    - /\/.*-mdh\/.*/
    - tags
  when: on_success

manual_deploy:
  stage: manual_deploy
  script:
    - sed -i 's/<shadeTestJar>true<\/shadeTestJar>/<shadeTestJar>false<\/shadeTestJar>/'  pom.xml
    - mvn deploy -s "tools/maven/settings.xml" -DskipTests -Dfast --fail-never
  only:
    - /\/.*-mdh\/.*/
  when: manual

manual_upload:
  stage: manual_upload
  script:
    - bash tools/upload.sh
  only:
    - /\/.*-mdh\/.*/
  when: manual

cleanup_job:
  stage: cleanup
  script:
    - mvn clean -s "tools/maven/settings.xml" 
  only:
    - /\/.*-mdh\/.*/
  when: always
