#!/usr/bin/env bash
. "$(dirname "$0")/_/husky.sh"

if ! git diff-index --cached --quiet HEAD -- "flink-runtime-web/web-dashboard/*"; then
  cd flink-runtime-web/web-dashboard && npm run lint-staged
fi
