/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.table.api.internal;

import org.apache.flink.annotation.Internal;
import org.apache.flink.core.execution.JobClient;
import org.apache.flink.types.Row;
import org.apache.flink.util.CloseableIterator;

/**
 * An internal class which helps the client to get the execute result from a specific sink.
 *
 * <p>This class is generated by specific sink and brings the result info to a TableResult.
 */
@Internal
public interface SelectResultProvider {
	/**
	 * Set the job client associated with the select job to retrieve the result.
	 */
	void setJobClient(JobClient jobClient);

	/**
	 * Returns the select result as row iterator.
	 */
	CloseableIterator<Row> getResultIterator();
}
