/***********************************************************************************************************************
 *
 * Copyright (C) 2010 by the Stratosphere project (http://stratosphere.eu)
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 **********************************************************************************************************************/

package eu.stratosphere.nephele.io.channels.bytebuffered;

import java.io.EOFException;
import java.io.IOException;

import eu.stratosphere.nephele.event.task.AbstractEvent;
import eu.stratosphere.nephele.event.task.AbstractTaskEvent;
import eu.stratosphere.nephele.io.InputGate;
import eu.stratosphere.nephele.io.RecordDeserializer;
import eu.stratosphere.nephele.io.channels.AbstractInputChannel;
import eu.stratosphere.nephele.io.channels.Buffer;
import eu.stratosphere.nephele.io.channels.ChannelID;
import eu.stratosphere.nephele.io.channels.ChannelType;
import eu.stratosphere.nephele.io.compression.CompressionEvent;
import eu.stratosphere.nephele.io.compression.CompressionLevel;
import eu.stratosphere.nephele.io.compression.Decompressor;
import eu.stratosphere.nephele.types.Record;

/**
 * Byte buffered input channels are a concrete implementation of input channels. Byte buffered input channels directly
 * read records to a TCP stream which is
 * generated by the corresponding network output channel. Two vertices connected by a network channel must run in the
 * same stage (i.e. at the same time) but may
 * run on different instances.
 * 
 * @author warneke
 * @param <T>
 *        the type of record that can be transported through this channel
 */
public abstract class AbstractByteBufferedInputChannel<T extends Record> extends AbstractInputChannel<T> {

	/**
	 * The deserializer used to deserialize records.
	 */
	private final RecordDeserializer<T> deserializer;

	/**
	 * Buffer for the uncompressed (raw) data.
	 */
	private Buffer dataBuffer;

	private ByteBufferedInputChannelBroker inputChannelBroker;

	/**
	 * The decompressor object to decompress incoming data
	 */
	private Decompressor decompressor = null;

	/**
	 * The exception observed in this channel while processing the buffers. Checked and thrown
	 * per-buffer.
	 */
	private volatile IOException ioException;

	/**
	 * Stores the number of bytes read through this input channel since its instantiation.
	 */
	private long amountOfDataTransmitted;

	private volatile boolean brokerAggreedToCloseChannel;

	/**
	 * Creates a new network input channel.
	 * 
	 * @param inputGate
	 *        the input gate this channel is wired to
	 * @param channelIndex
	 *        the channel's index at the associated input gate
	 * @param type
	 *        the type of record transported through this channel
	 * @param channelID
	 *        the ID of the channel
	 * @param connectedChannelID
	 *        the ID of the channel this channel is connected to
	 * @param compressionLevel
	 *        the level of compression to be used for this channel
	 */
	public AbstractByteBufferedInputChannel(final InputGate<T> inputGate, final int channelIndex,
			final RecordDeserializer<T> deserializer, final ChannelID channelID, final ChannelID connectedChannelID,
			final CompressionLevel compressionLevel) {
		super(inputGate, channelIndex, channelID, connectedChannelID, compressionLevel);
		this.deserializer = deserializer;
	}

	/**
	 * Deserializes the next record from one of the data buffers.
	 * 
	 * @return the next record or <code>null</code> if all data buffers are exhausted
	 * @throws ExecutionFailureException
	 *         if the record cannot be deserialized
	 */
	private T deserializeNextRecord(final T target) throws IOException {

		if (this.dataBuffer == null) {

			if (this.ioException != null) {
				throw this.ioException;
			}

			requestReadBufferFromBroker();

			if (this.dataBuffer == null) {
				return null;
			}

			if (this.decompressor != null) {
				this.dataBuffer = this.decompressor.decompress(this.dataBuffer);
			}
		}

		final T nextRecord = this.deserializer.readData(target, this.dataBuffer);

		if (this.dataBuffer.remaining() == 0) {
			releasedConsumedReadBuffer();
		}

		return nextRecord;
	}

	private void requestReadBufferFromBroker() {

		// this.leasedReadBuffer = this.inputChannelBroker.getReadBufferToConsume();
		final Buffer buffer = this.inputChannelBroker.getReadBufferToConsume();

		if (buffer == null) {
			return;
		}

		this.dataBuffer = buffer;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public T readRecord(final T target) throws IOException {

		if (isClosed()) {
			throw new EOFException();
		}

		return deserializeNextRecord(target);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean isClosed() throws IOException {

		if (this.dataBuffer != null) {
			return false;
		}

		if (this.ioException != null) {
			throw this.ioException;
		}

		if (!this.brokerAggreedToCloseChannel) {
			return false;
		}

		return true;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void close() throws IOException, InterruptedException {

		this.deserializer.clear();
		if (this.dataBuffer != null) {
			releasedConsumedReadBuffer();
		}

		// This code fragment makes sure the isClosed method works in case the channel input has not been fully consumed
		if (this.getType() == ChannelType.NETWORK) {
			if (!this.brokerAggreedToCloseChannel) {
				while (!this.brokerAggreedToCloseChannel) {

					requestReadBufferFromBroker();
					if (this.dataBuffer != null) {
						releasedConsumedReadBuffer();
					}
					Thread.sleep(500);
				}
			}
		}

		/*
		 * Send close event to indicate the input channel has successfully
		 * processed all data it is interested in.
		 */
		final ChannelType type = getType();
		if (type == ChannelType.NETWORK || type == ChannelType.INMEMORY) {
			transferEvent(new ByteBufferedChannelCloseEvent());
		}
	}

	private void releasedConsumedReadBuffer() {

		// Keep track of number of bytes transmitted through this channel
		this.amountOfDataTransmitted += this.dataBuffer.size();

		this.inputChannelBroker.releaseConsumedReadBuffer(this.dataBuffer);
		this.dataBuffer = null;
	}

	public void setInputChannelBroker(ByteBufferedInputChannelBroker inputChannelBroker) {
		this.inputChannelBroker = inputChannelBroker;
	}

	public void setDecompressor(final Decompressor decompressor) {
		this.decompressor = decompressor;
	}

	public void checkForNetworkEvents() {

		// Create an event for the input gate queue
		this.getInputGate().notifyRecordIsAvailable(getChannelIndex());
	}

	@Override
	public void processEvent(AbstractEvent event) {

		if (ByteBufferedChannelCloseEvent.class.isInstance(event)) {
			// System.out.println("Received close event");
			this.brokerAggreedToCloseChannel = true;
			// Make sure the application wake's up to check this
			checkForNetworkEvents();
		} else if (AbstractTaskEvent.class.isInstance(event)) {
			// Simply dispatch the event if it comes from a task
			getInputGate().deliverEvent((AbstractTaskEvent) event);
		} else if (CompressionEvent.class.isInstance(event)) {
			final CompressionEvent compressionEvent = (CompressionEvent) event;
			this.decompressor.setCurrentInternalDecompressionLibraryIndex(compressionEvent
				.getCurrentInternalCompressionLibraryIndex());
		} else {
			// TODO: Handle unknown event
			System.out.println("Received unknown event:" + event);
		}
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void transferEvent(AbstractEvent event) throws IOException, InterruptedException {

		this.inputChannelBroker.transferEventToOutputChannel(event);
	}

	public void reportIOException(IOException ioe) {

		this.ioException = ioe;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void releaseAllResources() {

		this.brokerAggreedToCloseChannel = true;

		this.deserializer.clear();

		// The buffers are recycled by the input channel wrapper

		if (this.decompressor != null) {
			this.decompressor.shutdown(getID());
		}
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void activate() throws IOException, InterruptedException {

		transferEvent(new ByteBufferedChannelActivateEvent());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public long getAmountOfDataTransmitted() {

		return this.amountOfDataTransmitted;
	}

	/**
	 * Notify the channel that a data unit has been consumed.
	 */
	public void notifyDataUnitConsumed() {

		this.getInputGate().notifyDataUnitConsumed(getChannelIndex());
	}
}
