# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- import_playbook: common.yaml

# NOTE: elasticsearch can't be ran under root.
- hosts: all
  become: no
  tasks:
    # Todo(wxy): Frocksdb doesn't have ARM release. Build and install it locally currently.
    - name: Build and install frocksdb
      shell:
        cmd: |
          git clone https://github.com/dataArtisans/frocksdb.git
          cd frocksdb
          git checkout origin/FRocksDB-5.17.2
          apt update
          apt install -y gcc g++ make
          export DEBUG_LEVEL=0
          make -j8 rocksdbjava

          mvn install:install-file -DgroupId=com.data-artisans \
          -DartifactId=frocksdbjni -Dversion=5.17.2-artisans-1.0 \
          -Dpackaging=jar -Dfile=java/target/rocksdbjni-5.17.2-linux64.jar
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    # Todo(wxy): Docker-compose doesn't have ARM package on ARM. Should fix this in Flink.
    # See: https://github.com/apache/flink/pull/9782
    - name: Comment out docker installation
      lineinfile:
        path: "/home/zuul/src/github.com/apache/flink/tools/travis/nightly.sh"
        regexp: "^.*setup_docker.sh"
        line: "# source ${HERE}/setup_docker.sh"

    # Todo(wxy):minikube doesn't support ARM . Should fix this in Flink.
    # See: https://github.com/apache/flink/pull/9782
    - name: Comment out k8s installation
      lineinfile:
        path: "/home/zuul/src/github.com/apache/flink/tools/travis/nightly.sh"
        regexp: "^.*setup_kubernetes.sh"
        line: "# source ${HERE}/setup_kubernetes.sh"

    # Todo(wxy): Remove this once git patch is not needed.
    - name: Add git author info
      shell:
        cmd: |
          git config --global user.email "info@openlabtesting.org"
          git config --global user.name "OpenLab"
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    # TODO(wxy): See: https://github.com/apache/flink/pull/9765
    - name: Disable xpack.ml for elasticsearch 6.0+
      shell:
        cmd: |
          set -xo pipefail

          cat << EOF >> Disable_xpack_ml.patch
          From 833d65d0455ca67cd04b3ce2be6b8e48100073ca Mon Sep 17 00:00:00 2001
          From: wangxiyuan <wangxiyuan1007@gmail.com>
          Date: Thu, 19 Sep 2019 15:20:51 +0800
          Subject: [PATCH] Update elasticsearch

          ---
           flink-end-to-end-tests/test-scripts/elasticsearch-common.sh | 6 ++++--
           flink-end-to-end-tests/test-scripts/test_sql_client.sh      | 2 +-
           .../test-scripts/test_streaming_elasticsearch.sh            | 2 +-
           3 files changed, 6 insertions(+), 4 deletions(-)

          diff --git a/flink-end-to-end-tests/test-scripts/elasticsearch-common.sh b/flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
          index 695905222f..9fae78efae 100644
          --- a/flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
          +++ b/flink-end-to-end-tests/test-scripts/elasticsearch-common.sh
          @@ -26,7 +26,7 @@ function setup_elasticsearch {
               mkdir -p \$TEST_DATA_DIR

               local downloadUrl=\$1
          -
          +    local elasticsearch_version=\${2-0}
               # start downloading Elasticsearch
               echo "Downloading Elasticsearch from \$downloadUrl ..."
               curl "\$downloadUrl" > \$TEST_DATA_DIR/elasticsearch.tar.gz
          @@ -34,7 +34,9 @@ function setup_elasticsearch {
               local elasticsearchDir=\$TEST_DATA_DIR/elasticsearch
               mkdir -p \$elasticsearchDir
               tar xzf \$TEST_DATA_DIR/elasticsearch.tar.gz -C \$elasticsearchDir --strip-components=1
          -
          +    if [ \$elasticsearch_version -ge 6 ]; then
          +      echo xpack.ml.enabled: false >> \$elasticsearchDir/config/elasticsearch.yml
          +    fi
               # start Elasticsearch cluster
               \$elasticsearchDir/bin/elasticsearch &
           }
          diff --git a/flink-end-to-end-tests/test-scripts/test_sql_client.sh b/flink-end-to-end-tests/test-scripts/test_sql_client.sh
          index 5798545279..262817ee6e 100755
          --- a/flink-end-to-end-tests/test-scripts/test_sql_client.sh
          +++ b/flink-end-to-end-tests/test-scripts/test_sql_client.sh
          @@ -101,7 +101,7 @@ echo "Preparing Elasticsearch..."
           ELASTICSEARCH_VERSION=6
           DOWNLOAD_URL='https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.1.tar.gz'

          -setup_elasticsearch \$DOWNLOAD_URL
          +setup_elasticsearch \$DOWNLOAD_URL \$ELASTICSEARCH_VERSION
           wait_elasticsearch_working

           ################################################################################
          diff --git a/flink-end-to-end-tests/test-scripts/test_streaming_elasticsearch.sh b/flink-end-to-end-tests/test-scripts/test_streaming_elasticsearch.sh
          index f37ee73d22..e2ee273d43 100755
          --- a/flink-end-to-end-tests/test-scripts/test_streaming_elasticsearch.sh
          +++ b/flink-end-to-end-tests/test-scripts/test_streaming_elasticsearch.sh
          @@ -25,7 +25,7 @@ DOWNLOAD_URL=\$2

           mkdir -p \$TEST_DATA_DIR

          -setup_elasticsearch \$DOWNLOAD_URL
          +setup_elasticsearch \$DOWNLOAD_URL \$ELASTICSEARCH_VERSION
           wait_elasticsearch_working

           start_cluster
          --
          2.21.0.windows.1
          EOF

          git am Disable_xpack_ml.patch
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    # TODO(wxy): See: https://github.com/apache/flink/pull/9768
    - name: Hacking add prometheus arm package
      lineinfile:
        path: "/home/zuul/src/github.com/apache/flink/flink-end-to-end-tests/flink-metrics-reporter-prometheus-test/src/test/java/org/apache/flink/metrics/prometheus/tests/PrometheusReporterEndToEndITCase.java"
        regexp: "^.*linux-amd64.*"
        line: "\t\t\t\tPROMETHEUS_FILE_NAME = base + \"linux-arm64\";"

    - name: Run split_misc.sh e2e test
      shell:
        cmd: |
          set -xo pipefail
          export PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -Dscala-2.12 -De2e-metrics"
          ./tools/travis/nightly.sh split_misc.sh
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'

    - name: Run split_misc_hadoopfree.sh e2e test
      shell:
        cmd: |
          set -xo pipefail
          export PROFILE="-Dinclude-hadoop -Dhadoop.version=2.8.3 -Dscala-2.12 -De2e-metrics"
          ./tools/travis/nightly.sh split_misc_hadoopfree.sh
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'
