/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.table.planner.codegen;

import org.apache.flink.api.common.functions.MapFunction;
import org.apache.flink.configuration.Configuration;
import org.apache.flink.table.data.GenericRowData;
import org.apache.flink.table.planner.calcite.FlinkTypeFactory;
import org.apache.flink.table.planner.calcite.FlinkTypeSystem;
import org.apache.flink.table.planner.codegen.calls.SearchOperatorGen;
import org.apache.flink.table.runtime.generated.GeneratedFunction;
import org.apache.flink.table.types.logical.BooleanType;
import org.apache.flink.table.types.logical.DoubleType;
import org.apache.flink.table.types.logical.FloatType;
import org.apache.flink.table.types.logical.LogicalType;
import org.apache.flink.table.types.logical.RowType;

import org.apache.calcite.rel.type.RelDataType;
import org.apache.calcite.rex.RexBuilder;
import org.apache.calcite.rex.RexCall;
import org.apache.calcite.rex.RexLiteral;
import org.apache.calcite.rex.RexNode;
import org.apache.calcite.rex.RexUnknownAs;
import org.apache.calcite.sql.fun.SqlStdOperatorTable;
import org.apache.calcite.util.Sarg;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.Arrays;
import java.util.stream.Collectors;

import scala.Option;

import static org.assertj.core.api.Assertions.assertThat;

/** Tests for the floating-point hash sets generated by {@link SearchOperatorGen}. */
class SearchOperatorGenTest {

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void testSignedZero(boolean singlePrecision) throws Exception {
        assertThat(Float.floatToRawIntBits(-0.0f)).isEqualTo(Integer.MIN_VALUE);
        assertThat(Double.doubleToRawLongBits(-0.0d)).isEqualTo(Long.MIN_VALUE);

        // Use approximate literals directly so decimal conversion cannot erase the zero sign.
        for (double[] points : new double[][] {{0.0d, 2.0d}, {-0.0d, 2.0d}, {-0.0d, 0.0d, 2.0d}}) {
            for (boolean negated : new boolean[] {false, true}) {
                final MapFunction function =
                        generateSearch(singlePrecision, negated, RexUnknownAs.UNKNOWN, points);
                assertThat(function.map(row(singlePrecision, -0.0d))).isEqualTo(!negated);
                assertThat(function.map(row(singlePrecision, 0.0d))).isEqualTo(!negated);
                assertThat(function.map(row(singlePrecision, 2.0d))).isEqualTo(!negated);
                assertThat(function.map(row(singlePrecision, 1.0d))).isEqualTo(negated);
                assertThat(function.map(GenericRowData.of((Object) null))).isNull();
            }
        }
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void testNonzeroAndSpecialValues(boolean singlePrecision) throws Exception {
        for (boolean negated : new boolean[] {false, true}) {
            final MapFunction function =
                    generateSearch(
                            singlePrecision,
                            negated,
                            RexUnknownAs.UNKNOWN,
                            2.0d,
                            Double.NaN,
                            Double.NEGATIVE_INFINITY,
                            Double.POSITIVE_INFINITY);
            assertThat(function.map(row(singlePrecision, -0.0d))).isEqualTo(negated);
            assertThat(function.map(row(singlePrecision, 0.0d))).isEqualTo(negated);
            assertThat(function.map(row(singlePrecision, 1.0d))).isEqualTo(negated);
            assertThat(function.map(row(singlePrecision, 2.0d))).isEqualTo(!negated);
            // Preserve the existing SEARCH semantics for NaN.
            assertThat(function.map(row(singlePrecision, Double.NaN))).isEqualTo(!negated);
            assertThat(function.map(row(singlePrecision, Double.NEGATIVE_INFINITY)))
                    .isEqualTo(!negated);
            assertThat(function.map(row(singlePrecision, Double.POSITIVE_INFINITY)))
                    .isEqualTo(!negated);
        }
    }

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void testNullHandling(boolean singlePrecision) throws Exception {
        for (RexUnknownAs nullAs : RexUnknownAs.values()) {
            final MapFunction function = generateSearch(singlePrecision, false, nullAs, 0.0d, 2.0d);
            assertThat(function.map(GenericRowData.of((Object) null)))
                    .isEqualTo(nullAs == RexUnknownAs.UNKNOWN ? null : nullAs == RexUnknownAs.TRUE);
        }
    }

    private static GenericRowData row(boolean singlePrecision, double value) {
        if (singlePrecision) {
            return GenericRowData.of((float) value);
        }
        return GenericRowData.of(value);
    }

    private static MapFunction generateSearch(
            boolean singlePrecision, boolean negated, RexUnknownAs nullAs, double... points) {
        final ClassLoader classLoader = SearchOperatorGenTest.class.getClassLoader();
        final LogicalType type = singlePrecision ? new FloatType() : new DoubleType();
        final FlinkTypeFactory typeFactory =
                new FlinkTypeFactory(classLoader, FlinkTypeSystem.INSTANCE);
        final RelDataType relType = typeFactory.createFieldTypeFromLogicalType(type);
        final RexBuilder builder = new RexBuilder(typeFactory);
        final RexCall in =
                (RexCall)
                        builder.makeIn(
                                builder.makeInputRef(relType, 0),
                                Arrays.stream(points)
                                        .mapToObj(
                                                point -> builder.makeApproxLiteral(point, relType))
                                        .collect(Collectors.toList()));
        final Sarg<?> sarg = ((RexLiteral) in.getOperands().get(1)).getValueAs(Sarg.class);
        assertThat(sarg.rangeSet.asRanges())
                .extracting(
                        range ->
                                Double.doubleToRawLongBits(
                                        ((Number) range.lowerEndpoint()).doubleValue()))
                .containsExactlyInAnyOrderElementsOf(
                        Arrays.stream(points)
                                .mapToObj(Double::doubleToRawLongBits)
                                .collect(Collectors.toList()));
        final RexNode search =
                builder.makeCall(
                        SqlStdOperatorTable.SEARCH,
                        builder.makeInputRef(relType, 0),
                        builder.makeSearchArgumentLiteral(
                                Sarg.of(nullAs, (negated ? sarg.negate() : sarg).rangeSet),
                                relType));
        final RowType inputType = RowType.of(type);
        final CodeGeneratorContext context =
                new CodeGeneratorContext(new Configuration(), classLoader);
        final GeneratedExpression expression =
                new ExprCodeGenerator(context, false)
                        .bindInput(inputType, "input", Option.empty())
                        .generateExpression(search);
        final GeneratedFunction<MapFunction> generated =
                FunctionCodeGenerator.generateFunction(
                        context,
                        "SearchFunction",
                        MapFunction.class,
                        expression.code()
                                + "\nreturn "
                                + expression.nullTerm()
                                + " ? null : "
                                + expression.resultTerm()
                                + ";",
                        new BooleanType(),
                        inputType,
                        "input",
                        Option.empty(),
                        Option.empty(),
                        "collector",
                        "context",
                        Option.empty());
        assertThat(generated.getCode())
                .contains(singlePrecision ? "FloatHashSet" : "DoubleHashSet")
                .contains(".contains(");
        return generated.newInstance(classLoader);
    }
}
