/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __de_tu_berlin_cit_nephele_io_compression_library_quicklz_QuicklzCompressor__
#define __de_tu_berlin_cit_nephele_io_compression_library_quicklz_QuicklzCompressor__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_de_tu_1berlin_cit_nephele_io_compression_library_quicklz_QuicklzCompressor_initIDs (JNIEnv *env, jclass);
JNIEXPORT jint JNICALL Java_de_tu_1berlin_cit_nephele_io_compression_library_quicklz_QuicklzCompressor_compressBytesDirect (JNIEnv *env, jobject, jint);

#ifdef __cplusplus
}
#endif

#endif /* __de_tu_berlin_cit_nephele_io_compression_library_quicklz_QuicklzCompressor__ */
