################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

source 'https://rubygems.org'

ruby '>= 2.4.0'

gem 'jekyll', '4.0.1'
gem 'addressable', '2.7.0'
gem 'octokit', '4.14.0'
gem 'therubyracer', '0.12.3'
gem 'json', '2.2.0'
gem 'jekyll-multiple-languages', '2.0.3'
gem 'jekyll-paginate', '1.1.0'
gem 'liquid-c', '4.0.0' # speed-up site generation
gem 'sassc', '2.2.1' # speed-up site generation

# group :jekyll_plugins do
#   gem 'hawkins'
# end
