name: flink-ci

on:
  push:
    branches: [release-1.16.1-fentik]
  pull_request:
    branches: [release-1.16.1-fentik]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    strategy:
      max-parallel: 4

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - run: |
          ./fentik-build.sh --package
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_EC2_METADATA_DISABLED: true

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#fentik-github'
        if: always()

