name: Spell checking
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request_target:
  issue_comment:
    types: [created]

jobs:
  build:
    name: Spell checker
    runs-on: ubuntu-20.04
    steps:
    - name: Check spelling
      uses: check-spelling/check-spelling@v0.0.20-alpha3
