name: Verify CEP Operator Flaky Test

on:
  push:
    branches: [ verify-cep-flaky-test ]
  workflow_dispatch:

jobs:
  verify-flaky-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Check out repository at specific commit
      uses: actions/checkout@v4
      with:
        ref: 23c9b5ac50d04d28a34a87c78eb2d3331c06b74b
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build and test without NonDex (should pass)
      run: |
        echo "Running test normally (should pass)"
        mvn test -pl flink-libraries/flink-cep -Dtest=org.apache.flink.cep.operator.CEPOperatorTest#testCEPOperatorCleanupEventTime
    
    - name: Install NonDex
      run: |
        echo "Installing NonDex"
        git clone https://github.com/TestingResearchIllinois/NonDex.git
        cd NonDex
        mvn install -DskipTests
    
    - name: Run test with NonDex (may fail, demonstrating flakiness)
      id: nondex_test
      continue-on-error: true
      run: |
        echo "Running test with NonDex (may fail due to flakiness)"
        mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -pl flink-libraries/flink-cep -Dtest=org.apache.flink.cep.operator.CEPOperatorTest#testCEPOperatorCleanupEventTime
    
    - name: Check NonDex results
      run: |
        echo "Checking NonDex results"
        if [ -d "flink-libraries/flink-cep/.nondex" ]; then
          echo "NonDex results found, indicating potential flakiness"
          ls -la flink-libraries/flink-cep/.nondex
          
          # Try to display summary if it exists
          SUMMARY_FILE=$(find flink-libraries/flink-cep/.nondex -name "summary.json" | head -1)
          if [ -n "$SUMMARY_FILE" ]; then
            echo "Summary file found: $SUMMARY_FILE"
            cat "$SUMMARY_FILE"
          fi
          
          # Check for failing tests
          FAILING_FILES=$(find flink-libraries/flink-cep/.nondex -name "*failures*" | head -1)
          if [ -n "$FAILING_FILES" ]; then
            echo "Failing tests found: $FAILING_FILES"
            cat "$FAILING_FILES"
            echo "Test is FLAKY: passes normally but fails with NonDex"
          fi
        else
          echo "No NonDex results found"
        fi
        
        # Check if the previous step failed
        if [ "${{ steps.nondex_test.outcome }}" == "failure" ]; then
          echo "NonDex run failed, which may indicate flakiness"
        fi